os: linux
language: node_js 
sudo: required
node_js:
  - 12  # 使用 nodejs LTS v10
branches:
  only:
    - source # 只监控 source 的 branch
cache:
  directories:
    - node_modules # 缓存 node_modules 加快构建速度
before_install: ## 根据你所用的主题和自定义的不同，这里会有所不同
  - npm install -g hexo-cli # 在 CI 环境内安装 Hexonpm install
install:
 - npm install # 在根目录安装站点需要的依赖 
 - npm install -S hexo-theme-icarus
 - ls
script:
  - hexo clean
  - hexo generate # generate static files
# deploy: # 根据个人情况，这里会有所不同
#   provider: pages
#   cleanup: true # 构建完成后不清除
#   token: $GH_TOKEN # 你刚刚设置的 token
#   keep_history: true # 保存历史
#   on:
#     branch: source # hexo 站点源文件所在的 branch
#   local_dir: public 
#   target_branch: master # 存放生成站点文件的 branch，使用 username.github.io 必须是 master
after_success:                # script 阶段成功时执行，构建失败不会执行，其他同上
  - git config --local user.name "travis-ci"
  - git config --local user.email "deploy@travis-ci.org"
  - sed -i'' "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo deploy > /dev/null   # 通过 Hexo 的 deploy 命令部署博客
